services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dvdrental_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped

  sqlpad:
    image: sqlpad/sqlpad:7.5.7
    hostname: "sqlpad"
    ports:
      - "3000:3000"
    environment:
      SQLPAD_ADMIN: ${SQLPAD_ADMIN}
      SQLPAD_ADMIN_PASSWORD: ${SQLPAD_ADMIN_PASSWORD}
      SQLPAD_APP_LOG_LEVEL: debug
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_SEED_DATA_PATH: /etc/sqlpad/seed-data
      SQLPAD_CONNECTIONS__pgdemo__name: ${POSTGRES_DB}
      SQLPAD_CONNECTIONS__pgdemo__driver: postgres
      SQLPAD_CONNECTIONS__pgdemo__host: postgres
      SQLPAD_CONNECTIONS__pgdemo__database: ${POSTGRES_DB}
      SQLPAD_CONNECTIONS__pgdemo__username: ${POSTGRES_USER}
      SQLPAD_CONNECTIONS__pgdemo__password: ${POSTGRES_PASSWORD}
      SQLPAD_CONNECTIONS__pgdemo__multiStatementTransactionEnabled: "true"
      SQLPAD_CONNECTIONS__pgdemo__idleTimeoutSeconds: 86400
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: dvdrental_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - pgadmin-log:/var/log/pgadmin

volumes:
  pgadmin-data:
  pgadmin-log:
